import { Component, OnInit } from '@angular/core';
import { filter, map, of, reduce, Subject } from 'rxjs';

@Component({
  selector: 'app-subscribe-example-two',
  templateUrl: './subscribe-example-two.component.html',
  styleUrls: ['./subscribe-example-two.component.scss']
})
export class SubscribeExampleTwoComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }
  loadData(){
    let subject = new Subject();

    

    subject.subscribe((result)=>{
      console.log(result+" Subscriber 1")
    })

    subject.subscribe((result)=>{
      console.log(result+"suibscriber 2")
    })

    subject.next("Data generated by 1")
  }

  getData(){
    let observableObj= of(2,13,14,35,66,57)
    let filterObj= observableObj.pipe(
      filter(x=>x%2==0),//2,14,66
      map(x=>x+1),//3,15,67
      reduce((acc,one)=>acc+one)//3+15+67=85
    ) 
    filterObj.subscribe((res)=>{
      console.log(res)//85
    })

  }


}
