import { Component, OnInit } from '@angular/core';
import { Observable, Subscriber } from 'rxjs';

@Component({
  selector: 'app-subscribe-example',
  templateUrl: './subscribe-example.component.html',
  styleUrls: ['./subscribe-example.component.scss']
})
export class SubscribeExampleComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }
  /**
   * @param  {} {letobservableObj=newObservable((subscriber
   * @param  {} =>{subscriber.next("Datagenerated1"
   * @param  {} subscriber.next("Datagenerated2"
   * @param  {} subscriber.error("ErrorOccuredwhilegeneratingdata"
   * @param  {} subscriber.next("Datagenerated3"
   * @param  {} setTimeout((
   * @param  {} =>{console.log("Datageneratedby4"
   * @param  {} }
   * @param  {} 3000
   * @param  {} ;}
   * @param  {any} observableObj.subscribe((res
   */
  getData() {

    let observableObj = new Observable((subscriber) => {
      subscriber.next("Data generated 1")
      subscriber.next("Data generated 2")
      subscriber.error("Error Occured while generating data")
      subscriber.next("Data generated 3")
      setTimeout(() => {
        console.log("Data generated by 4")
      }, 3000);

    })

    observableObj.subscribe(
      (res: any) => { console.log(res); },
      (err: any) => { console.log(err) },
      () => {
        console.log("Task is completed")
      }

    );
  }

}
